# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pypa-build
      run: python -m pip install build

    - name: Create wheel and sdist
      run: python -m build -s -w --outdir dist .

    - name: Upload sdist
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz

    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl

  test-wheels:
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2

    - name: Download wheel
      uses: actions/download-artifact@v4.1.7
      with:
        name: wheel
        path: dist

    - name: Run Unit Tests
      shell: bash
      run: |
        python -m pip install dist/*
        python -m unittest discover tests -v

  test-wheels-27:
    runs-on: ubuntu-latest
    container: python:2.7.18
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Download wheel
        uses: actions/download-artifact@v4.1.7
        with:
          name: wheel
          path: dist

      - name: Run Unit Tests
        shell: bash
        run: |
          python2 -m pip install dist/*
          python2 -m unittest discover tests -v

  latest-release:
    needs:
      - test-wheels
      - test-wheels-27
    runs-on: ubuntu-latest
    steps:
      - name: Download sdist
        uses: actions/download-artifact@v4.1.7
        with:
          name: sdist
          path: dist

      - name: Download wheel
        uses: actions/download-artifact@v4.1.7
        with:
          name: wheel
          path: dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/*.tar.gz
            dist/*.whl
